### ISSUE TITLE
Entity Testing ToDo List

### ISSUE THREAD

**Issue by IrakliK** [SirSeim/Deeg#10]
- [x] Program
- [x] Block
- [x] Type
- [ ] ForStatement
  - [x] StdFor
  - [ ] StdForIdExp
  - [x] CountFor
  - [x] CountsFor
- [x] IfStatement
  - [x] ElseIfStatment
  - [x] ElseStatement
- [x] WhileStatement
- [x] ReturnStatement
- [ ] ClassDefinition
- [x] VariableDeclaration
  - [ ] VariableAssignment
  - [ ] VariableExpression
- [x] Args
- [ ] ExpList
- [ ] FunctionExp
- [ ] Params
- [ ] ParamList
- [ ] TrailingIf
- [ ] VariableReference
- [ ] FieldAccess
- [ ] IterableItem
- [ ] Range
- [x] IntegerLiteral
- [x] FloatLiteral
- [x] BooleanLiteral
- [x] StringLiteral
- [x] List
- [x] Dict
- [x] BindingList
- [x] Binding
- [x] BinaryExpression
- [x] UnaryExpression
- [ ] Function //

**Comment by SirSeim** [comment]
Why did you close the issue?

**Comment by SirSeim** [comment]
@mreid10 make sure to check off items as you go. I'd only check ones that have an actual test running, not one that is written but is commented out.
