### ISSUE TITLE
Exp ordering

### ISSUE THREAD

**Issue by SirSeim** [SirSeim/Deeg#12]
As it stands right now, this is our order of Exp:

```
Exp0           ::=  Exp1 ('if' Exp1 ('else' Exp1)?)?
Exp1           ::=  Exp2 ('or' Exp2)*
Exp2           ::=  Exp3 ('and' Exp3)*
Exp3           ::=  Exp4 (relop Exp4)?
Exp4           ::=  Exp5 (('thru'|'till') Exp5 ('by' Exp5)?)?
Exp5           ::=  Exp6 (addop Exp6)*
Exp6           ::=  Exp7 (mulop Exp7)*
Exp7           ::=  prefixop? Exp8
Exp8           ::=  Exp9 ('**' Exp5)?
Exp9           ::=  Exp10 ('.' Exp10 | '[' Exp4 ']' | Args)*
Exp10          ::=  boollit | intlit | floatlit | id | '(' Exp ')' | stringlit
                 | DictLit | ListLit
```

My question pertains to the ordering of the math operations and their interior Exp references.
For a piece of code like `3 ** 4 + 5` this ordering of Grammar means the result is `(** 3 (+ 4 5))`. Would it make more sense for it to be `(+ (** 3 4) 5)` so if you wanted `(** 3 (+ 4 5))` you'd have to do `3 ** (4 + 5)`. If the later is the case, does that mean that instead of putting `Exp8` above `Exp5` we should instead replace the `Exp5` reference within `Exp8` to `Exp9`, aka make `Exp8`:

```
Exp8           ::=  Exp9 ('**' Exp9)?
```

I'm also wondering if `Exp7` should be placed below `Exp8`. Under the current ordering, `-3 ** -4` creates `(UnaryOp - (BinaryOp ** 3 (UnaryOp - 4)))` Switching as suggested would hopefully create `(BinaryOp ** (UnaryOp - 3) (UnaryOp - 4))`.

Any comments on these subjects?

**Comment by rtoal** [comment]
Yes on the first one, 8 -> 9 9

Probably no on the second, to stay in line with Python.
