### ISSUE TITLE
README Suggestions

### ISSUE THREAD

**Issue by rtoal** [SirSeim/Deeg#5]
Things to clean/add
- [x] You claim indent-based syntax as a feature, but you use a terminal `end`
- [x] Reword "Optional type specify with ?" to be consistent with line above; 
- [x] Can slices be like `[2, 5 till 10, 12, 7]`?
- [x] In Array/Lists section you have the word `prints`
- [x] Think about `>` for pattern matching, since you might have a `>` in an expression
- [x] One larger example needed

**Comment by SirSeim** [comment]
> Can slices be like `[2, 5 till 10, 12, 7]`?

No, they must be in the form `[num till num (by num)]`

> In Array/Lists section you have the word `prints`

`prints` is a globally accessible function, like `console.log`
